# Generated by Django 2.2.2 on 2019-06-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
