# Generated by Django 2.2.2 on 2019-06-25 20:53

import apps.drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.drive.models.file_directory_path),
        ),
    ]
