# Generated by Django 2.2.2 on 2019-06-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_auto_20190625_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extention',
        ),
    ]
