# Generated by Django 2.2.2 on 2019-06-25 21:19

import apps.drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_auto_20190625_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=apps.drive.models.file_directory_path),
        ),
    ]
