# Generated by Django 2.2.2 on 2019-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0011_auto_20190626_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
