# Generated by Django 2.2.2 on 2019-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0012_auto_20190626_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
