# Generated by Django 2.2.2 on 2019-06-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0013_auto_20190626_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created']},
        ),
    ]
