# Generated by Django 2.2.2 on 2019-06-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0015_auto_20190626_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(default='0 bytes', max_length=50),
        ),
    ]
