# Generated by Django 2.2.2 on 2019-06-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0016_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
    ]
