# Generated by Django 2.2.2 on 2019-07-06 05:39

import apps.drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0017_remove_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=3500, upload_to=apps.drive.models.file_directory_path),
        ),
    ]
